### ISSUE TITLE
Error at start: [Errno -2] Name or service not known

### ISSUE THREAD

**Issue by davesayers2014** [oe-alliance/XMLTV-Import#30]
With the latest changes I am now receiving

[EPGImport] nextImport, source= IPTV
[EPGImport] Downloading: http://xxxx to local path: /tmp/epgimport
[EPGImport] Not cheching the server since nocheck is set for it: http://xxxx
[EPGImport] Error at start: [Errno -2] Name or service not known

If I revert to earlier commit it works fine

**Comment by jenseneverest** [comment]
Glad it is not just me, i am not sure the nocheck="1" is actually working.  TBH i would like someone to explain in more detail where and what exactly should be done on the server side. I can see the need for a check, sort of....

**Comment by davesayers2014** [comment]
nocheck="1" does work see here https://www.world-of-satellite.com/showthread.php?60020-EPG-Importer-Down&p=474780&viewfull=1#post474780

**Comment by pr2git** [comment]
Please provide me with the file content that generate this problem.
xxx.sources.xml and then the downloaded file.

**Comment by pr2git** [comment]
@jenseneverest 

When you upload files to your server and that everything went fine, you need to create a file:
LastUpdate.txt

Just containing the date in format:  YYYY-mm-dd
Exemple: 2018-9-17

(Be careful we had to change from LastUpdate.log to LastUpdate.txt since some servers prevent to send .log files).

We assume that the data files are uploaded daily on the server. So we tolerate a delta between the current date and the LastUpdate.txt date of 2 days (so 3 days or more we reject the server).

That's all you need to do, of course if you always create this file even when the upload failed then this file become totally useless.

The idea behind this file is to avoid that I server send back obsolete data files. This already happened in the past, where a server still hold obsolete files and provide them back to end-user, but Rytec was unable to upload to this server anymore (so it was not possible to suppress the file neither).

But anyway nocheck="1" should also work for XMLTVImport.

**Comment by jenseneverest** [comment]
Thanks for the reply guys, With the latest pure2 image rytec sources are working,  but mine are not, with that image the log suggests that the nocheck="1" is not working at least for my sources.

I then flashed todays openATV 6.2 and all Rytec source are not working, the log is the same as @davesayers2014 has attached above. But at least the nocheck is working with todays atv image on my source lol.... (i see it bypass the check in the log) i then also have the same issue as Rytec sources.

I am now about to flash openPLI and will test again, if i still have issue with openPLI i will post to the pli forum thread @pr2git started.

TIA

**Comment by pr2git** [comment]
I think you should remove the IPv6 stuff from XMLTVImport.

**Comment by Schimmelreiter** [comment]
I think we shouldn't have blindly replaced a complete file.
Neither did I with other plugins, I always checked if our branch contained enhancements compared to PLi.

If you want 100% PLi, install OpenPLi.

Anyways, ATM I'm working on a solution.

**Comment by Ev0-BH** [comment]
Seems to be fixed now

**Comment by AbuBaniaz** [comment]
Fixed with this commit
https://github.com/oe-alliance/XMLTV-Import/commit/4166ac766a72841a58a4adb0a8eb3094fe8f8ef2

**Comment by jenseneverest** [comment]
it is still not quite right guys

https://github.com/oe-alliance/XMLTV-Import/issues/33
